
import jsPDF from 'jspdf';

interface QuestionnaireData {
  fullName: string;
  date: Date | undefined;
  signature: string;
  answers: Record<number, boolean>;
}

const medicalQuestions = [
  "Do you have any allergies to medications?",
  "Are you currently taking any prescription medications?",
  "Do you have a history of heart disease?",
  "Have you ever had high blood pressure?",
  "Do you have diabetes or a family history of diabetes?",
  "Have you ever been diagnosed with cancer?",
  "Do you smoke or have you smoked in the past?",
  "Do you consume alcohol regularly?",
  "Have you had any surgeries in the past 5 years?",
  "Do you have any chronic pain conditions?",
  "Are you currently experiencing any symptoms?",
  "Do you have a history of mental health conditions?",
  "Have you ever had kidney or liver problems?",
  "Do you have any breathing difficulties or asthma?",
  "Are you pregnant or planning to become pregnant?",
  "Do you have any vision or hearing problems?",
  "Have you ever had blood clots or circulation issues?",
  "Do you have any skin conditions or rashes?",
  "Are you up to date with your vaccinations?",
  "Do you exercise regularly or maintain an active lifestyle?"
];

export const generateQuestionnairePDF = (data: QuestionnaireData) => {
  const pdf = new jsPDF();
  
  // Set font
  pdf.setFont('helvetica');
  
  // Title
  pdf.setFontSize(20);
  pdf.setTextColor(37, 99, 235); // Blue color
  pdf.text('Medical Questionnaire Report', 20, 30);
  
  // Patient Information
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Patient Information', 20, 50);
  
  pdf.setFontSize(12);
  pdf.text(`Name: ${data.fullName}`, 20, 65);
  pdf.text(`Date: ${data.date ? data.date.toLocaleDateString() : 'Not specified'}`, 20, 75);
  
  // Questionnaire Summary
  pdf.setFontSize(16);
  pdf.text('Questionnaire Summary', 20, 95);
  
  pdf.setFontSize(12);
  pdf.text('Total Questions: 20', 20, 110);
  pdf.text('Status: Completed', 20, 120);
  pdf.text(`Completion Date: ${new Date().toLocaleDateString()}`, 20, 130);
  
  // Questions and Answers
  pdf.setFontSize(16);
  pdf.text('Questions and Answers', 20, 150);
  
  let yPosition = 165;
  pdf.setFontSize(10);
  
  medicalQuestions.forEach((question, index) => {
    // Check if we need a new page
    if (yPosition > 260) {
      pdf.addPage();
      yPosition = 20;
    }
    
    const answer = data.answers[index] ? 'Yes' : 'No';
    const questionText = `${index + 1}. ${question}`;
    const answerText = `Answer: ${answer}`;
    
    // Split long questions into multiple lines if needed
    const splitQuestion = pdf.splitTextToSize(questionText, 170);
    
    pdf.text(splitQuestion, 20, yPosition);
    yPosition += splitQuestion.length * 5;
    
    pdf.setTextColor(37, 99, 235);
    pdf.text(answerText, 20, yPosition);
    pdf.setTextColor(0, 0, 0);
    yPosition += 10;
  });
  
  // Add signature if available (on a new page if needed)
  if (data.signature) {
    if (yPosition > 200) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(16);
    pdf.text('Digital Signature', 20, yPosition);
    
    try {
      // Add signature image
      pdf.addImage(data.signature, 'PNG', 20, yPosition + 10, 100, 40);
    } catch (error) {
      console.warn('Could not add signature to PDF:', error);
      pdf.setFontSize(12);
      pdf.text('Signature captured (unable to display in PDF)', 20, yPosition + 20);
    }
  }
  
  // Footer on last page
  const pageCount = pdf.getNumberOfPages();
  pdf.setPage(pageCount);
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Medical Questionnaire System', 20, 280);
  
  return pdf;
};
